### ISSUE TITLE
wrong doc, no working exemple

### ISSUE THREAD

**Issue by ornoone** [millerf/django-channels2-jsonrpc#1]
hi, i Just landed on your project, which seem to be the only one to provide jsonRPC capability to django-channels, but your repo is fare from being usable.

the link to a better doc is broken in the readme : 

> It is intended to be used as a Websocket consumer. See documentation except... simplier...

and your method `JsonRpcWebsocketConsumer.notify_group` don't exists, and no method look like it.

I praise the effort to provide a lib for this need, which I'm sure is a common use case for many of us, but please, don't ruin it with not working example and undocumented project.

you are the only result on google, this is a great occasion to gain good visibility with a simple but working lib like this.

**Comment by millerf** [comment]
Fixed.

I had done a copy of the version for channels 1 and  forgot to remove the "Notification" part, as it is now handled quite differently in channels 2 now.

**Comment by ornoone** [comment]
thanks for your rapidity.
