### ISSUE TITLE
Async methods inside the rpc_method()

### ISSUE THREAD

**Issue by LittlePony** [millerf/django-channels2-jsonrpc#2]
Сan't make them work.

**Comment by millerf** [comment]
Hi @LittlePony,

A more detailed description of the error (code snippets, expected behaviour, happening behaviour) would be useful...

And some salutations as well :p

**Comment by LittlePony** [comment]
```
class Consumer(AsyncJsonRpcWebsocketConsumer):
	pass


@Consumer.rpc_method('chat_join')
async def chat_join(session_id, **kwargs):
    consumer = kwargs["consumer"]
    await consumer.channel_layer.group_add(
        f'chat_{session_id}',
        consumer.channel_name
    )
    return '__JOINED__'
```

TypeError: Object of type 'coroutine' is not JSON serializable

**Comment by LittlePony** [comment]
I think decorator should be:

```
@classmethod
def asyn_rpc_method(cls, rpc_name=None, websocket=True, http=True):
    async def wrap(f):
        ...
```

**Comment by millerf** [comment]
Good point. You might be right.

If you want, you can create a MR, with a new method for RpcBase that implement `async_rpc_method`, or I'll look into that later...

**Comment by LittlePony** [comment]
https://github.com/millerf/django-channels2-jsonrpc/blob/f5aa36f164fbda98e2d224c9ac233233ecc60ea9/channels_jsonrpc/jsonrpcconsumer.py#L296

Method that returns a coroutine object that cannot be serialized.

**Comment by LittlePony** [comment]
https://github.com/LittlePony/django-channels2-jsonrpc/commit/c61f61f13827ff96c2f4c78f7fa6c06e646b5ed1
Works as expected with these changes

**Comment by millerf** [comment]
Very nice! Sorry about that, I had never used the Async part...

Could you create a Merge Request and I’ll create a new release…

**Comment by millerf** [comment]
Version 1.4.0 has been deployed.

Thanks a lot for your help.
